# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  # web-server
  config.vm.define "web" do |web|
    web.vm.hostname = "dm-web-server.loc"
    web.vm.box = "debian/stretch64"
    web.vm.box_version = "9.7.0"
    web.vm.synced_folder "./../dm-site/", "/var/www/dm-site", id: "vagrant-root", :group=>'nginx', :mount_options=>['dmode=775,fmode=775']
    web.vm.network :private_network, ip: "192.168.10.10"
  end

  # database server
  config.vm.define "db" do |db|
    db.vm.hostname = "dm-db.loc"
    db.vm.box = "debian/stretch64"
    db.vm.box_version = "9.7.0"
    db.vm.network :private_network, ip: "192.168.10.20"
  end
end
